server:
  port: 8082
spring:
  mail:
    username: 2195496026@qq.com
    password: fdsbxxwwzbpudiac
    host: smtp.qq.com
    default-encoding: UTF-8
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cheer_vote?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password:
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


logging:
  level:
    cn:
      newtol: debug
  path: weiXin
  pattern:
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n"
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"



defaultKey:
  VaildCode: VaildCode
  headimgurl: http://main.newtol.cn/default.jpg
  SMSUrl: https://api.miaodiyun.com/20150822/industrySMS/sendSMS
  SMSAccountSid: 91b23a40561a454b96c3d818b4c5e514
  SMSAuthToken: 5b441ab6151e424ab59881a913b14993